import React, { useRef, useState, useEffect } from 'react';
import { Canvas, useFrame } from '@react-three/fiber';
import { OrbitControls, PerspectiveCamera, useGLTF, useAnimations, Center } from '@react-three/drei';
import * as THREE from 'three';
import { API_URL } from '../api';

/**
 * OpenSim Native GLTF Visualizer
 * Loads the output .gltf generated by opensim-viewer-backend.
 */
const OpenSimModel = ({ modelUrl }) => {
    // URL passed down already contains the cache-busting timestamp
    const { scene, animations } = useGLTF(modelUrl);
    const groupRef = useRef();

    // Play any animations present in the GLTF (which contains the .sto motion!)
    // Now that the backend generates completely static poses, this might be empty,
    // which is perfectly fine.
    const { actions, names } = useAnimations(animations, groupRef);

    useEffect(() => {
        if (names && names.length > 0 && actions) {
            // Play the first available animation
            const action = actions[names[0]];
            if (action) {
                action.reset().fadeIn(0.5).play();
                action.setLoop(THREE.LoopOnce, 1);
                action.clampWhenFinished = true;
            }
        }
        
        // Cleanup function to clear the object from memory when URL changes
        return () => {
            useGLTF.clear(modelUrl);
        }
    }, [actions, names, modelUrl, scene]); // re-run if a new modelUrl forces reload

    // Fix scaling or positioning if needed (OpenSim coordinates vs Three.js)
    // CRITICAL: We MUST clone the scene so React Three Fiber doesn't reuse the old bone positions
    // from the cached model mesh when the URL changes.
    const clonedScene = React.useMemo(() => scene.clone(true), [scene]);

    return (
        <group ref={groupRef} position={[0, -2, 0]} scale={5} rotation={[0, Math.PI, 0]}>
            <Center>
                <primitive object={clonedScene} />
            </Center>
        </group>
    );
};

import { Text } from '@react-three/drei';

// Pre-load a fallback geometry while loading OpenSim model, or if the model isn't built yet
const FallbackBox = () => (
    <group>
        <mesh position={[0, 0, 0]}>
            <boxGeometry args={[1, 1, 1]} />
            <meshStandardMaterial color="#333" wireframe />
        </mesh>
        <Text
            position={[0, 1.5, 0]}
            color="white"
            fontSize={0.5}
            maxWidth={200}
            lineHeight={1}
            letterSpacing={0.02}
            textAlign={'center'}
        >
            Generating Simulation...
        </Text>
    </group>
);


const Hand3D = ({ activeChannels, amplitude, duration, jointAngles, executeSignal, isExecuting, gltfFilename = "test_model.gltf" }) => {
    // Generate a new forced update key whenever channels change to force the GLTF to reload
    const [refreshKey, setRefreshKey] = useState(Date.now());
    const [isGenerating, setIsGenerating] = useState(false);

    useEffect(() => {
        if (!executeSignal || executeSignal === 0) return;
        setIsGenerating(true);
    }, [executeSignal]);

    // Backend now waits for simulation to complete before returning. Show model when API returns (isExecuting=false).
    useEffect(() => {
        if (executeSignal && !isExecuting) {
            setRefreshKey(Date.now());
            setIsGenerating(false);
        }
    }, [executeSignal, isExecuting, gltfFilename]);


    return (
        <div className="w-full h-full bg-gray-900 rounded-xl overflow-hidden shadow-2xl border border-gray-700 relative">
            <Canvas>
                <PerspectiveCamera makeDefault position={[0, 2, 8]} />
                <OrbitControls enableZoom={true} />

                <ambientLight intensity={1.5} />
                <directionalLight position={[10, 10, 10]} intensity={2.5} />
                <spotLight position={[-10, 0, 20]} angle={0.3} />

                {isGenerating ? (
                    <FallbackBox />
                ) : (
                    <React.Suspense fallback={<FallbackBox />}>
                        <OpenSimModel key={refreshKey} modelUrl={`${API_URL}/static/${gltfFilename}?t=${refreshKey}`} />
                    </React.Suspense>
                )}

                <gridHelper args={[10, 10, 0x444444, 0x222222]} rotation={[Math.PI / 2, 0, 0]} position={[0, -2, 0]} />
            </Canvas>

            {/* Overlay Info */}
            <div className="absolute top-4 right-4 bg-black/60 p-2 text-xs text-green-400 font-mono rounded pointer-events-none">
                <p>OPENSIM NATIVE VIEWER</p>
                <p>CH: {activeChannels && activeChannels.length > 0 ? activeChannels.join(", ") : "IDLE"}</p>
                {amplitude > 0 && <p>AMP: {amplitude}mA</p>}
            </div>
        </div>
    );
};

export default Hand3D;
